//! WIT export layer for the `logic-core-component` world.
//!
//! Thin adapter only: every exported call first asks the host-authored
//! `crate::custom_*` hook for this runner function; `None` (the template
//! default) falls back to the minimal in-memory behavior implemented here.
//! Do not edit this file to customize behavior — edit the `custom_*`
//! functions in `src/lib.rs`.
//!
//! Pattern follows `examples/logic-hooks-template/src/component.rs` and
//! `antikythera-sdk/src/wasm_exports.rs`: `wit_bindgen::generate!` against
//! the root wit, a unit struct implementing
//! `exports::antikythera::agent_sdk::runner::Guest`, and `export!`.
//!
//! ## Structured not-implemented error
//!
//! Every runner function whose template default is unimplemented returns the
//! JSON object `{"error":"not implemented","function":"<name>"}` as the
//! `Err` string — `name` is the WIT kebab-case function name. The format is
//! a single consistent choice (documented here and in `lib.rs`) so host code
//! can detect a "template hole" deterministically via the `"error"` field.
//!
//! ## In-memory session store
//!
//! `init` / `get-state` / `reset-session` are backed by a process-global
//! `HashMap<String, serde_json::Value>`. The stored value has the SDK's
//! `AgentState` JSON shape (see `antikythera-sdk/src/wasm_agent/types.rs`),
//! so host code reading `get-state` sees the same fields it sees from the
//! composite SDK:
//!
//! ```json
//! {
//!   "session_id": "...", "current_step": 0, "message_history": [],
//!   "tool_results": {}, "config": { ... }, "rolling_summary": null,
//!   "fsm_state": "idle"
//! }
//! ```

// wit-bindgen emits pre-2024-edition export shims; the unsafe-op-in-
// unsafe-fn lint fires inside the generated code, not our wrapper.
#![allow(unsafe_op_in_unsafe_fn)]
// Export layer is wasm-gated; dead on native targets.
#![allow(dead_code)]

wit_bindgen::generate!({
    world: "logic-core-component",
    path: "../../../wit/antikythera.wit",
});

use std::collections::HashMap;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Mutex, OnceLock};

/// Structured not-implemented error: `{"error":"not implemented","function":"<name>"}`.
fn not_implemented(function: &str) -> String {
    format!(r#"{{"error":"not implemented","function":"{function}"}}"#)
}

fn lock_poisoned() -> String {
    "Internal error: logic-core-template session store lock poisoned".to_string()
}

static SESSION_COUNTER: AtomicU64 = AtomicU64::new(0);

fn new_session_id() -> String {
    let ts_ns = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0);
    let seq = SESSION_COUNTER.fetch_add(1, Ordering::Relaxed);
    format!("session-{ts_ns}-{seq}")
}

fn sessions() -> &'static Mutex<HashMap<String, serde_json::Value>> {
    static SESSIONS: OnceLock<Mutex<HashMap<String, serde_json::Value>>> = OnceLock::new();
    SESSIONS.get_or_init(|| Mutex::new(HashMap::new()))
}

/// Template default for `init`: build an `AgentState`-shaped JSON record from
/// the config, store it under the session id (reuse-or-create, matching the
/// SDK's `sessions.entry(...).or_insert_with(...)`), and return the session
/// id — the SDK runner's return contract is a bare id string, not JSON.
fn default_init(config_json: &str) -> Result<String, String> {
    let config: serde_json::Value = serde_json::from_str(config_json)
        .map_err(|e| format!("Configuration failed: Invalid config-json: {e}"))?;

    let session_id = config
        .get("session_id")
        .and_then(serde_json::Value::as_str)
        .map(str::to_string)
        .unwrap_or_else(new_session_id);

    let state = serde_json::json!({
        "session_id": session_id,
        "current_step": 0,
        "message_history": [],
        "tool_results": {},
        "config": {
            "max_steps": config.get("max_steps").and_then(serde_json::Value::as_u64).unwrap_or(10),
            "verbose": config.get("verbose").and_then(serde_json::Value::as_bool).unwrap_or(false),
            "auto_execute_tools": config.get("auto_execute_tools").and_then(serde_json::Value::as_bool).unwrap_or(true),
            "session_timeout_secs": config.get("session_timeout_secs").and_then(serde_json::Value::as_u64).unwrap_or(300),
            "session_id": session_id,
            "context_policy": config.get("context_policy").cloned().unwrap_or_else(|| serde_json::json!({
                "max_history_messages": 24,
                "summarize_after_messages": 12,
                "summary_max_chars": 1200,
                "truncation_strategy": "keep_newest",
            })),
        },
        "rolling_summary": null,
        "fsm_state": "idle",
    });

    sessions()
        .lock()
        .map_err(|_| lock_poisoned())?
        .entry(session_id.clone())
        .or_insert(state);

    Ok(session_id)
}

struct LogicCoreTemplate;

impl exports::antikythera::agent_sdk::runner::Guest for LogicCoreTemplate {
    fn init(config_json: String) -> Result<String, String> {
        match crate::custom_init(&config_json) {
            Some(session_id) => Ok(session_id),
            None => default_init(&config_json),
        }
    }

    fn prepare_user_turn(request_json: String) -> Result<String, String> {
        match crate::custom_prepare_turn(&request_json) {
            Some(prepared) => Ok(prepared),
            None => Err(not_implemented("prepare-user-turn")),
        }
    }

    fn commit_llm_response(
        prepared_turn_json: String,
        llm_response_json: String,
    ) -> Result<String, String> {
        match crate::custom_commit_response(&prepared_turn_json, &llm_response_json) {
            Some(commit) => Ok(commit),
            None => Err(not_implemented("commit-llm-response")),
        }
    }

    fn commit_llm_stream(prepared_turn_json: String) -> Result<String, String> {
        match crate::custom_commit_stream(&prepared_turn_json) {
            Some(commit) => Ok(commit),
            None => Err(not_implemented("commit-llm-stream")),
        }
    }

    fn process_llm_response_for_session(
        session_id: String,
        llm_response_json: String,
    ) -> Result<String, String> {
        match crate::custom_process_llm_response(&session_id, &llm_response_json) {
            Some(action) => Ok(action),
            None => Err(not_implemented("process-llm-response-for-session")),
        }
    }

    fn process_tool_result_for_session(
        session_id: String,
        tool_result_json: String,
    ) -> Result<String, String> {
        match crate::custom_process_tool_result(&session_id, &tool_result_json) {
            Some(result) => Ok(result),
            None => Err(not_implemented("process-tool-result-for-session")),
        }
    }

    fn append_llm_chunk(
        session_id: String,
        chunk: String,
        correlation_id: Option<String>,
    ) -> Result<bool, String> {
        match crate::custom_append_chunk(&session_id, &chunk, correlation_id.as_deref()) {
            Some(ok) => Ok(ok),
            None => Err(not_implemented("append-llm-chunk")),
        }
    }

    fn drain_events(session_id: String) -> Result<String, String> {
        match crate::custom_drain_events(&session_id) {
            Some(events) => Ok(events),
            None => Err(not_implemented("drain-events")),
        }
    }

    fn get_state(session_id: String) -> Result<String, String> {
        sessions()
            .lock()
            .map_err(|_| lock_poisoned())?
            .get(&session_id)
            .map(serde_json::Value::to_string)
            .ok_or_else(|| format!("Session not found: {session_id}"))
    }

    fn reset_session(session_id: String) -> Result<bool, String> {
        let removed = sessions()
            .lock()
            .map_err(|_| lock_poisoned())?
            .remove(&session_id)
            .is_some();
        Ok(removed)
    }

    fn sweep_idle_sessions(now_unix_ms: Option<i64>) -> Result<u32, String> {
        match crate::custom_sweep_idle(now_unix_ms) {
            Some(reaped) => Ok(reaped),
            None => Err(not_implemented("sweep-idle-sessions")),
        }
    }

    fn register_tools(tools_json: String) -> Result<u32, String> {
        match crate::custom_register_tools(&tools_json) {
            Some(count) => Ok(count),
            None => Err(not_implemented("register-tools")),
        }
    }

    fn get_tools_prompt() -> Result<String, String> {
        match crate::custom_get_tools_prompt() {
            Some(prompt) => Ok(prompt),
            None => Err(not_implemented("get-tools-prompt")),
        }
    }

    fn set_context_policy(policy_json: String) -> Result<bool, String> {
        match crate::custom_set_context_policy(&policy_json) {
            Some(ok) => Ok(ok),
            None => Err(not_implemented("set-context-policy")),
        }
    }

    fn get_telemetry_snapshot(session_id: String) -> Result<String, String> {
        match crate::custom_get_telemetry(&session_id) {
            Some(snapshot) => Ok(snapshot),
            None => Err(not_implemented("get-telemetry-snapshot")),
        }
    }

    fn get_slo_snapshot(session_id: String) -> Result<String, String> {
        match crate::custom_get_slo(&session_id) {
            Some(snapshot) => Ok(snapshot),
            None => Err(not_implemented("get-slo-snapshot")),
        }
    }
}

// Wasm-only: WIT export names break rustc's ld version script on native cdylibs.
#[cfg(target_family = "wasm")]
export!(LogicCoreTemplate);
