// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod antikythera {
        pub mod agent_sdk {
            /// ToolRegistry - stateless tool definition catalog and builtin executor.
            ///
            /// Contract exported by the standalone `antikythera-toolrunner`
            /// component and imported by the SDK component; `wasm-tools
            /// compose` wires the two. The interface carries no state (D4): every call
            /// is self-contained and all payloads travel as JSON strings, consistent
            /// with the JSON-string philosophy of `runner`.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod tool_registry {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_list_tools_json_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::list_tools_json();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(e) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                            let vec2 = (e.into_bytes()).into_boxed_slice();
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            ::core::mem::forget(vec2);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr2.cast_mut();
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let vec3 = (e.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_list_tools_json<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_validate_tool_call_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let result2 = T::validate_tool_call(
                        _rt::string_lift(bytes0),
                        _rt::string_lift(bytes1),
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result2 {
                        Ok(_) => {
                            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Err(e) => {
                            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                            let vec4 = (e.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    };
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_validate_tool_call<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_execute_builtin_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let result2 = T::execute_builtin(
                        _rt::string_lift(bytes0),
                        _rt::string_lift(bytes1),
                        arg4 as u32,
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result2 {
                        Ok(e) => {
                            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                            let vec4 = (e.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                        Err(e) => {
                            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                            let vec5 = (e.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                    };
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_execute_builtin<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// List the known tool definitions as a JSON array string.
                    ///
                    /// Each element is a ToolDefinition JSON object:
                    ///   { "name", "title"?, "description", "parameters"?,
                    ///     "input_schema"?, "output_schema"? }
                    /// The array is sorted by tool name for determinism
                    /// (`ToolRegistry::to_json`).
                    ///
                    /// Ok - JSON array of ToolDefinition.
                    /// Err - the registry could not be serialized.
                    fn list_tools_json() -> Result<_rt::String, _rt::String>;
                    /// Validate a tool call against the registry.
                    ///
                    /// Ok - the call is valid.
                    /// Err(message) - the tool is unknown or a required parameter is missing
                    /// (`ToolRegistry::validate_call` failure).
                    ///
                    /// An empty registry skips validation and accepts any tool, mirroring
                    /// `ToolRegistry::validate_call`.
                    fn validate_tool_call(
                        tool_name: _rt::String,
                        arguments_json: _rt::String,
                    ) -> Result<(), _rt::String>;
                    /// Execute a builtin tool and return its result as a JSON string.
                    ///
                    /// Ok - JSON ToolResult object:
                    ///   { "name", "success", "output", "error"?, "step_id" }
                    /// - the exact shape produced by `tool_result_to_json`, identical to the
                    ///   SDK's WASM `ToolResult` mirror, so the composite can deserialize it
                    ///   without field translation.
                    ///
                    /// Err - signal, not a tool failure:
                    /// - "tool '<name>' requires host execution (not builtin)" means the tool
                    ///   has no builtin handler in this component; the caller MUST delegate
                    ///   execution to the host (existing `process_tool_result_for_session`
                    ///   flow);
                    /// - any other message means the call was rejected before execution
                    ///   (validation failure or malformed arguments).
                    ///
                    /// A tool failure is NOT an error: it is returned as Ok with
                    /// `success: false` and an `error` message.
                    fn execute_builtin(
                        tool_name: _rt::String,
                        arguments_json: _rt::String,
                        step_id: u32,
                    ) -> Result<_rt::String, _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_antikythera_agent_sdk_tool_registry_1_0_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "antikythera:agent-sdk/tool-registry@1.0.0#list-tools-json")]
                        unsafe extern "C" fn export_list_tools_json() -> * mut u8 {
                        unsafe { $($path_to_types)*:: _export_list_tools_json_cabi::<$ty
                        > () } } #[unsafe (export_name =
                        "cabi_post_antikythera:agent-sdk/tool-registry@1.0.0#list-tools-json")]
                        unsafe extern "C" fn _post_return_list_tools_json(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_list_tools_json::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "antikythera:agent-sdk/tool-registry@1.0.0#validate-tool-call")]
                        unsafe extern "C" fn export_validate_tool_call(arg0 : * mut u8,
                        arg1 : usize, arg2 : * mut u8, arg3 : usize,) -> * mut u8 {
                        unsafe { $($path_to_types)*::
                        _export_validate_tool_call_cabi::<$ty > (arg0, arg1, arg2, arg3)
                        } } #[unsafe (export_name =
                        "cabi_post_antikythera:agent-sdk/tool-registry@1.0.0#validate-tool-call")]
                        unsafe extern "C" fn _post_return_validate_tool_call(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_validate_tool_call::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "antikythera:agent-sdk/tool-registry@1.0.0#execute-builtin")]
                        unsafe extern "C" fn export_execute_builtin(arg0 : * mut u8, arg1
                        : usize, arg2 : * mut u8, arg3 : usize, arg4 : i32,) -> * mut u8
                        { unsafe { $($path_to_types)*::
                        _export_execute_builtin_cabi::<$ty > (arg0, arg1, arg2, arg3,
                        arg4) } } #[unsafe (export_name =
                        "cabi_post_antikythera:agent-sdk/tool-registry@1.0.0#execute-builtin")]
                        unsafe extern "C" fn _post_return_execute_builtin(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_execute_builtin::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_antikythera_agent_sdk_tool_registry_1_0_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 3 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 3
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_tool_registry_component_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::antikythera::agent_sdk::tool_registry::__export_antikythera_agent_sdk_tool_registry_1_0_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::antikythera::agent_sdk::tool_registry);
    };
}
#[doc(inline)]
pub(crate) use __export_tool_registry_component_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:antikythera:agent-sdk@1.0.0:tool-registry-component:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 405] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x87\x02\x01A\x02\x01\
A\x02\x01B\x08\x01j\x01s\x01s\x01@\0\0\0\x04\0\x0flist-tools-json\x01\x01\x01j\0\
\x01s\x01@\x02\x09tool-names\x0earguments-jsons\0\x02\x04\0\x12validate-tool-cal\
l\x01\x03\x01@\x03\x09tool-names\x0earguments-jsons\x07step-idy\0\0\x04\0\x0fexe\
cute-builtin\x01\x04\x04\0)antikythera:agent-sdk/tool-registry@1.0.0\x05\0\x04\0\
3antikythera:agent-sdk/tool-registry-component@1.0.0\x04\0\x0b\x1d\x01\0\x17tool\
-registry-component\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-compo\
nent\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
