// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod antikythera {
        pub mod agent_sdk {
            /// LogicHooks - host-authored plug-and-play pipeline hooks.
            ///
            /// Contract imported by the SDK component and exported by a host-authored
            /// hooks component (`logic-hooks-component`); `wasm-tools compose` wires the
            /// two, mirroring the `tool-registry` / `antikythera-toolrunner` pair. The
            /// SDK runner calls each hook at a fixed pipeline point and uses the returned
            /// JSON as the decision for that point:
            ///
            /// - Ok `{"passthrough": true}` - use the SDK default behavior at this point;
            ///   the passthrough signal is exactly this single-key object, any other JSON
            ///   object is an override;
            /// - Ok <override JSON> - use this value in place of the SDK default; the
            ///   meaning of the override is defined per function below;
            /// - Err(message) - the hook failed; the SDK aborts the operation and
            ///   surfaces the error to the caller. A failing hook never falls back to
            ///   passthrough.
            ///
            /// The returned string MUST be a JSON object; an unparseable or non-object
            /// return is treated as a hook failure (Err-path semantics).
            ///
            /// Hooks are pure decision functions: they receive inputs and return a
            /// decision. Session state is owned by the SDK - it is passed in as
            /// `session-state-json` on every call, and hooks MUST NOT persist or mutate
            /// it; any state a hook writes is discarded.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod logic_hooks {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_prepare_turn_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let result2 = T::prepare_turn(
                        _rt::string_lift(bytes0),
                        _rt::string_lift(bytes1),
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result2 {
                        Ok(e) => {
                            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                            let vec4 = (e.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                        Err(e) => {
                            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                            let vec5 = (e.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                    };
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_prepare_turn<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_decide_action_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let result2 = T::decide_action(
                        _rt::string_lift(bytes0),
                        _rt::string_lift(bytes1),
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result2 {
                        Ok(e) => {
                            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                            let vec4 = (e.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                        Err(e) => {
                            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                            let vec5 = (e.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                    };
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_decide_action<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_handle_tool_result_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let result2 = T::handle_tool_result(
                        _rt::string_lift(bytes0),
                        _rt::string_lift(bytes1),
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result2 {
                        Ok(e) => {
                            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                            let vec4 = (e.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                        Err(e) => {
                            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                            let vec5 = (e.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                    };
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_handle_tool_result<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                        _ => {
                            let l3 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Prepare a user turn (prompt building + tool guidance).
                    ///
                    /// Invoked at the start of `runner.prepare-user-turn`, after the SDK has
                    /// built its default prepared turn.
                    ///
                    /// - `request-json` - the request payload passed to `prepare-user-turn`.
                    /// - `session-state-json` - the session agent-state JSON snapshot.
                    ///
                    /// Ok `{"passthrough": true}` - keep the SDK default prepared turn.
                    /// Ok <prepared-turn JSON> - use this JSON as the prepared turn; present
                    ///   fields are authoritative, absent fields fall back to the SDK default.
                    ///   A hook that appends a message returns the full `messages` array.
                    /// Err(message) - abort the turn and surface the error.
                    fn prepare_turn(
                        request_json: _rt::String,
                        session_state_json: _rt::String,
                    ) -> Result<_rt::String, _rt::String>;
                    /// Decide the action for a committed LLM response.
                    ///
                    /// Invoked by the SDK when an LLM response is committed
                    /// (`process-llm-response-for-session`), before the default action
                    /// derivation runs.
                    ///
                    /// - `session-state-json` - the session agent-state JSON snapshot.
                    /// - `llm-response-json` - the committed LLM response JSON.
                    ///
                    /// Ok `{"passthrough": true}` - keep the SDK default action decision.
                    /// Ok <decision JSON> - override the decision; the SDK commits this value
                    ///   as the action result. A hook can force a terminal action (for
                    ///   example `final`) by returning the same envelope the SDK produces for
                    ///   that action.
                    /// Err(message) - abort the operation and surface the error.
                    fn decide_action(
                        session_state_json: _rt::String,
                        llm_response_json: _rt::String,
                    ) -> Result<_rt::String, _rt::String>;
                    /// Handle a tool result before it is committed to the session.
                    ///
                    /// Invoked by the SDK when a tool result is reported
                    /// (`process-tool-result-for-session`), before default processing.
                    ///
                    /// - `session-state-json` - the session agent-state JSON snapshot.
                    /// - `tool-result-json` - the reported tool result JSON.
                    ///
                    /// Ok `{"passthrough": true}` - keep the SDK default tool-result processing.
                    /// Ok <tool-result JSON> - use this JSON as the tool result in place of
                    ///   the reported one.
                    /// Err(message) - abort the operation and surface the error.
                    fn handle_tool_result(
                        session_state_json: _rt::String,
                        tool_result_json: _rt::String,
                    ) -> Result<_rt::String, _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_antikythera_agent_sdk_logic_hooks_1_0_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "antikythera:agent-sdk/logic-hooks@1.0.0#prepare-turn")] unsafe
                        extern "C" fn export_prepare_turn(arg0 : * mut u8, arg1 : usize,
                        arg2 : * mut u8, arg3 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_prepare_turn_cabi::<$ty > (arg0,
                        arg1, arg2, arg3) } } #[unsafe (export_name =
                        "cabi_post_antikythera:agent-sdk/logic-hooks@1.0.0#prepare-turn")]
                        unsafe extern "C" fn _post_return_prepare_turn(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*:: __post_return_prepare_turn::<$ty
                        > (arg0) } } #[unsafe (export_name =
                        "antikythera:agent-sdk/logic-hooks@1.0.0#decide-action")] unsafe
                        extern "C" fn export_decide_action(arg0 : * mut u8, arg1 : usize,
                        arg2 : * mut u8, arg3 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_decide_action_cabi::<$ty > (arg0,
                        arg1, arg2, arg3) } } #[unsafe (export_name =
                        "cabi_post_antikythera:agent-sdk/logic-hooks@1.0.0#decide-action")]
                        unsafe extern "C" fn _post_return_decide_action(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*:: __post_return_decide_action::<$ty
                        > (arg0) } } #[unsafe (export_name =
                        "antikythera:agent-sdk/logic-hooks@1.0.0#handle-tool-result")]
                        unsafe extern "C" fn export_handle_tool_result(arg0 : * mut u8,
                        arg1 : usize, arg2 : * mut u8, arg3 : usize,) -> * mut u8 {
                        unsafe { $($path_to_types)*::
                        _export_handle_tool_result_cabi::<$ty > (arg0, arg1, arg2, arg3)
                        } } #[unsafe (export_name =
                        "cabi_post_antikythera:agent-sdk/logic-hooks@1.0.0#handle-tool-result")]
                        unsafe extern "C" fn _post_return_handle_tool_result(arg0 : * mut
                        u8,) { unsafe { $($path_to_types)*::
                        __post_return_handle_tool_result::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_antikythera_agent_sdk_logic_hooks_1_0_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 3 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 3
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::string::String;
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_logic_hooks_component_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::antikythera::agent_sdk::logic_hooks::__export_antikythera_agent_sdk_logic_hooks_1_0_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::antikythera::agent_sdk::logic_hooks);
    };
}
#[doc(inline)]
pub(crate) use __export_logic_hooks_component_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:antikythera:agent-sdk@1.0.0:logic-hooks-component:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 437] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xa9\x02\x01A\x02\x01\
A\x02\x01B\x07\x01j\x01s\x01s\x01@\x02\x0crequest-jsons\x12session-state-jsons\0\
\0\x04\0\x0cprepare-turn\x01\x01\x01@\x02\x12session-state-jsons\x11llm-response\
-jsons\0\0\x04\0\x0ddecide-action\x01\x02\x01@\x02\x12session-state-jsons\x10too\
l-result-jsons\0\0\x04\0\x12handle-tool-result\x01\x03\x04\0'antikythera:agent-s\
dk/logic-hooks@1.0.0\x05\0\x04\01antikythera:agent-sdk/logic-hooks-component@1.0\
.0\x04\0\x0b\x1b\x01\0\x15logic-hooks-component\x03\0\0\0G\x09producers\x01\x0cp\
rocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
