//! Client configuration generator
//!
//! Generates and modifies client.toml containing:
//! - `[[providers]]` - API provider configurations
//! - `[[servers]]` - MCP server definitions
//! - `[server]` - REST settings (CORS, docs)

use crate::constants::CONFIG_PATH;
use crate::logging::ConfigLogger;
use std::error::Error;
use std::fs;
use std::path::Path;

/// Generate the client configuration file with a generic provider entry.
///
/// The `provider_type` is an opaque discriminator — core does not interpret it.
/// Each provider adapter (OpenAI, Gemini, Ollama, etc.) is responsible for
/// mapping its own configuration fields.
pub fn generate(
    provider_id: &str,
    provider_type: &str,
    endpoint: &str,
    api_key_env: &str,
    models: &[(String, String)],
) -> Result<(), Box<dyn Error>> {
    let log = ConfigLogger::new("config");

    let models_toml: String = models
        .iter()
        .map(|(name, display)| {
            format!(
                "    {{ name = \"{}\", display_name = \"{}\" }}",
                name, display
            )
        })
        .collect::<Vec<String>>()
        .join(",\n");

    log.debug(format!(
        "Rendering client config template | provider={}",
        provider_id
    ));

    let config_content = format!(
        r#"# MCP Client Configuration
# Generated by setup wizard

# REST Server Settings
[server]
cors_origins = []

# Providers
[[providers]]
id = "{provider_id}"
type = "{provider_type}"
endpoint = "{endpoint}"
api_key = "{api_key_env}"
models = [
{models_toml}
]
"#,
        provider_id = provider_id,
        provider_type = provider_type,
        endpoint = endpoint,
        api_key_env = api_key_env,
        models_toml = models_toml,
    );

    fs::create_dir_all("config").map_err(|e| {
        log.error(format!(
            "Failed to create config directory | path=config error={}",
            e
        ));
        e
    })?;
    log.info(format!("Writing config | path={}", CONFIG_PATH));
    fs::write(CONFIG_PATH, config_content).map_err(|e| {
        log.error(format!(
            "Failed to write config | path={} error={}",
            CONFIG_PATH, e
        ));
        e
    })?;

    log.info(format!(
        "Config generated successfully | path={}",
        CONFIG_PATH
    ));
    Ok(())
}

/// Generate the .env file with API keys
pub fn generate_env(api_key_env: &str, api_key: &str) -> Result<(), Box<dyn Error>> {
    let log = ConfigLogger::new("config");
    let env_path = Path::new(".env");

    let content = if env_path.exists() {
        log.info(format!(
            "Reading existing .env | path={}",
            env_path.display()
        ));
        let existing = fs::read_to_string(env_path).map_err(|e| {
            log.error(format!(
                "Failed to read .env | path={} error={}",
                env_path.display(),
                e
            ));
            e
        })?;
        if existing.contains(&format!("{}=", api_key_env)) {
            existing
                .lines()
                .map(|line| {
                    if line.starts_with(&format!("{}=", api_key_env)) {
                        format!("{}={}", api_key_env, api_key)
                    } else {
                        line.to_string()
                    }
                })
                .collect::<Vec<String>>()
                .join("\n")
        } else {
            let suffix = if existing.ends_with('\n') || existing.is_empty() {
                ""
            } else {
                "\n"
            };
            format!("{}{}{}={}\n", existing, suffix, api_key_env, api_key)
        }
    } else {
        format!("{}={}\n", api_key_env, api_key)
    };

    log.info(format!("Writing .env | path={}", env_path.display()));
    fs::write(env_path, content).map_err(|e| {
        log.error(format!(
            "Failed to write .env | path={} error={}",
            env_path.display(),
            e
        ));
        e
    })?;

    Ok(())
}

/// Add a new provider to the config
pub fn add_provider(
    provider_id: &str,
    provider_type: &str,
    endpoint: &str,
    api_key_env: Option<&str>,
) -> Result<(), Box<dyn Error>> {
    let log = ConfigLogger::new("config");
    let config_path = Path::new(CONFIG_PATH);

    log.info(format!("Reading config | path={}", config_path.display()));
    let content = fs::read_to_string(config_path).map_err(|e| {
        log.error(format!(
            "Failed to read config | path={} error={}",
            config_path.display(),
            e
        ));
        e
    })?;
    let mut new_provider = format!(
        r#"

[[providers]]
id = "{}"
type = "{}"
endpoint = "{}""#,
        provider_id, provider_type, endpoint
    );

    if let Some(key) = api_key_env {
        new_provider.push_str(&format!("\napi_key = \"{}\"", key));
    }
    let updated = format!("{}\n{}", content.trim_end(), new_provider);
    log.info(format!(
        "Writing config with new provider | provider={} path={}",
        provider_id,
        config_path.display()
    ));
    fs::write(config_path, updated).map_err(|e| {
        log.error(format!(
            "Failed to write config | path={} error={}",
            config_path.display(),
            e
        ));
        e
    })?;

    Ok(())
}

/// Update provider settings in config
pub fn update_provider(
    provider_id: &str,
    new_endpoint: &str,
    new_api_key_env: &str,
) -> Result<(), Box<dyn Error>> {
    let log = ConfigLogger::new("config");
    let config_path = Path::new(CONFIG_PATH);

    log.info(format!("Reading config | path={}", config_path.display()));
    let content = fs::read_to_string(config_path).map_err(|e| {
        log.error(format!(
            "Failed to read config | path={} error={}",
            config_path.display(),
            e
        ));
        e
    })?;
    let mut lines: Vec<String> = content.lines().map(String::from).collect();
    let mut in_target_provider = false;

    for line in &mut lines {
        if line.contains("[[providers]]") {
            in_target_provider = false;
        }
        if line.starts_with(&format!("id = \"{}\"", provider_id)) {
            in_target_provider = true;
        }

        if in_target_provider {
            if line.starts_with("endpoint = ") {
                *line = format!("endpoint = \"{}\"", new_endpoint);
            }
            if line.starts_with("api_key = ") {
                *line = format!("api_key = \"{}\"", new_api_key_env);
            }
        }
    }

    log.info(format!(
        "Writing updated provider | provider={} path={}",
        provider_id,
        config_path.display()
    ));
    fs::write(config_path, lines.join("\n")).map_err(|e| {
        log.error(format!(
            "Failed to write config | path={} error={}",
            config_path.display(),
            e
        ));
        e
    })?;
    Ok(())
}

/// Add a model to a provider
pub fn add_model_to_provider(
    provider_id: &str,
    model_name: &str,
    display_name: &str,
) -> Result<(), Box<dyn Error>> {
    let log = ConfigLogger::new("config");
    let config_path = Path::new(CONFIG_PATH);

    log.info(format!("Reading config | path={}", config_path.display()));
    let content = fs::read_to_string(config_path).map_err(|e| {
        log.error(format!(
            "Failed to read config | path={} error={}",
            config_path.display(),
            e
        ));
        e
    })?;
    let new_model = format!(
        "    {{ name = \"{}\", display_name = \"{}\" }}",
        model_name, display_name
    );
    let mut result = String::new();
    let mut in_target_provider = false;
    let mut found_models = false;

    for line in content.lines() {
        if line.contains("[[providers]]") {
            in_target_provider = false;
        }
        if line.contains(&format!("id = \"{}\"", provider_id)) {
            in_target_provider = true;
        }

        if in_target_provider && line.starts_with("models = [") {
            found_models = true;
        }
        if in_target_provider && found_models && line.trim() == "]" {
            result.push_str(",\n");
            result.push_str(&new_model);
            result.push('\n');
            found_models = false;
        }

        result.push_str(line);
        result.push('\n');
    }

    log.info(format!(
        "Writing config with new model | model={} provider={} path={}",
        model_name,
        provider_id,
        config_path.display()
    ));
    fs::write(config_path, result).map_err(|e| {
        log.error(format!(
            "Failed to write config | path={} error={}",
            config_path.display(),
            e
        ));
        e
    })?;
    Ok(())
}

/// Remove a model from a provider
pub fn remove_model_from_provider(
    provider_id: &str,
    model_name: &str,
) -> Result<(), Box<dyn Error>> {
    let log = ConfigLogger::new("config");
    let config_path = Path::new(CONFIG_PATH);

    log.info(format!("Reading config | path={}", config_path.display()));
    let content = fs::read_to_string(config_path).map_err(|e| {
        log.error(format!(
            "Failed to read config | path={} error={}",
            config_path.display(),
            e
        ));
        e
    })?;

    let mut result = String::new();
    let mut in_target_provider = false;
    let mut in_models_array = false;

    for line in content.lines() {
        if line.contains("[[providers]]") {
            in_target_provider = false;
            in_models_array = false;
        }
        if line.contains(&format!("id = \"{}\"", provider_id)) {
            in_target_provider = true;
        }
        if in_target_provider && line.starts_with("models = [") {
            in_models_array = true;
        }
        if in_models_array && line.trim() == "]" {
            in_models_array = false;
        }
        if in_models_array && line.contains(&format!("name = \"{}\"", model_name)) {
            continue;
        }

        result.push_str(line);
        result.push('\n');
    }

    log.info(format!(
        "Writing config after removing model | model={} provider={} path={}",
        model_name,
        provider_id,
        config_path.display()
    ));
    fs::write(config_path, result).map_err(|e| {
        log.error(format!(
            "Failed to write config | path={} error={}",
            config_path.display(),
            e
        ));
        e
    })?;
    Ok(())
}

/// Add a server to the config
pub fn add_server(name: &str, command: &str, args: &[String]) -> Result<(), Box<dyn Error>> {
    let log = ConfigLogger::new("config");
    let config_path = Path::new(CONFIG_PATH);

    if !config_path.exists() {
        log.error(format!(
            "Config file not found | path={}",
            config_path.display()
        ));
        return Err("Config file not found. Run setup wizard first.".into());
    }

    log.info(format!("Reading config | path={}", config_path.display()));
    let mut content = fs::read_to_string(config_path).map_err(|e| {
        log.error(format!(
            "Failed to read config | path={} error={}",
            config_path.display(),
            e
        ));
        e
    })?;

    let args_toml = if args.is_empty() {
        String::new()
    } else {
        format!(
            "\nargs = [{}]",
            args.iter()
                .map(|a| format!("\"{}\"", a))
                .collect::<Vec<String>>()
                .join(", ")
        )
    };

    let server_block = format!(
        r#"

[[servers]]
name = "{}"
command = "{}"{}"#,
        name, command, args_toml
    );

    content.push_str(&server_block);
    log.info(format!(
        "Writing config with new server | server={} path={}",
        name,
        config_path.display()
    ));
    fs::write(config_path, content).map_err(|e| {
        log.error(format!(
            "Failed to write config | path={} error={}",
            config_path.display(),
            e
        ));
        e
    })?;

    Ok(())
}

/// Add an HTTP server to the config
pub fn add_http_server(
    name: &str,
    url: &str,
    headers: &std::collections::HashMap<String, String>,
) -> Result<(), Box<dyn Error>> {
    let log = ConfigLogger::new("config");
    let config_path = Path::new(CONFIG_PATH);

    if !config_path.exists() {
        log.error(format!(
            "Config file not found | path={}",
            config_path.display()
        ));
        return Err("Config file not found. Run setup wizard first.".into());
    }

    log.info(format!("Reading config | path={}", config_path.display()));
    let mut content = fs::read_to_string(config_path).map_err(|e| {
        log.error(format!(
            "Failed to read config | path={} error={}",
            config_path.display(),
            e
        ));
        e
    })?;

    let headers_toml = if headers.is_empty() {
        String::new()
    } else {
        let pairs: Vec<String> = headers
            .iter()
            .map(|(k, v)| format!("{} = \"{}\"", k, v))
            .collect();
        format!("\nheaders = {{ {} }}", pairs.join(", "))
    };

    let server_block = format!(
        r#"

[[servers]]
name = "{}"
url = "{}"{}"#,
        name, url, headers_toml
    );

    content.push_str(&server_block);
    log.info(format!(
        "Writing config with new HTTP server | server={} path={}",
        name,
        config_path.display()
    ));
    fs::write(config_path, content).map_err(|e| {
        log.error(format!(
            "Failed to write config | path={} error={}",
            config_path.display(),
            e
        ));
        e
    })?;

    Ok(())
}

/// Remove a server from the config
pub fn remove_server(server_name: &str) -> Result<(), Box<dyn Error>> {
    let log = ConfigLogger::new("config");
    let config_path = Path::new(CONFIG_PATH);

    log.info(format!("Reading config | path={}", config_path.display()));
    let content = fs::read_to_string(config_path).map_err(|e| {
        log.error(format!(
            "Failed to read config | path={} error={}",
            config_path.display(),
            e
        ));
        e
    })?;

    let mut result = String::new();
    let mut skip_section = false;
    let mut blank_line_buffer = String::new();

    for line in content.lines() {
        if line.trim() == "[[servers]]" {
            if skip_section {
                skip_section = false;
            }
            blank_line_buffer.clear();
        }
        if line.contains(&format!("name = \"{}\"", server_name)) {
            skip_section = true;
            if result.ends_with("[[servers]]\n") {
                result.truncate(result.len() - "[[servers]]\n".len());
            }
        }
        if line.is_empty() {
            blank_line_buffer.push('\n');
            continue;
        }

        if !skip_section {
            result.push_str(&blank_line_buffer);
            blank_line_buffer.clear();
            result.push_str(line);
            result.push('\n');
        }
    }

    log.info(format!(
        "Writing config after removing server | server={} path={}",
        server_name,
        config_path.display()
    ));
    fs::write(config_path, result.trim_end()).map_err(|e| {
        log.error(format!(
            "Failed to write config | path={} error={}",
            config_path.display(),
            e
        ));
        e
    })?;
    Ok(())
}

/// Get current CORS origins from config
pub fn get_cors_origins() -> Result<Vec<String>, Box<dyn Error>> {
    let log = ConfigLogger::new("config");
    let config_path = Path::new(CONFIG_PATH);

    log.info(format!("Reading config | path={}", config_path.display()));
    let content = fs::read_to_string(config_path).map_err(|e| {
        log.error(format!(
            "Failed to read config | path={} error={}",
            config_path.display(),
            e
        ));
        e
    })?;

    let mut origins = Vec::new();
    let mut in_cors_array = false;

    for line in content.lines() {
        let trimmed = line.trim();

        if trimmed.starts_with("cors_origins") && trimmed.contains('[') {
            in_cors_array = true;
            // Handle inline array like: cors_origins = ["origin1", "origin2"]
            if let Some(start) = trimmed.find('[')
                && let Some(end) = trimmed.find(']')
            {
                let array_content = &trimmed[start + 1..end];
                for item in array_content.split(',') {
                    let cleaned = item.trim().trim_matches('"').trim_matches('\'');
                    if !cleaned.is_empty() {
                        origins.push(cleaned.to_string());
                    }
                }
                in_cors_array = false;
            }
            continue;
        }

        if in_cors_array {
            if trimmed == "]" {
                in_cors_array = false;
                continue;
            }
            // Extract origin from line like: "http://localhost:8080",
            let cleaned = trimmed
                .trim_end_matches(',')
                .trim_matches('"')
                .trim_matches('\'');
            if !cleaned.is_empty() {
                origins.push(cleaned.to_string());
            }
        }
    }

    Ok(origins)
}

/// Add a CORS origin to the config
pub fn add_cors_origin(origin: &str) -> Result<(), Box<dyn Error>> {
    let log = ConfigLogger::new("config");
    let config_path = Path::new(CONFIG_PATH);

    log.info(format!("Reading config | path={}", config_path.display()));
    let content = fs::read_to_string(config_path).map_err(|e| {
        log.error(format!(
            "Failed to read config | path={} error={}",
            config_path.display(),
            e
        ));
        e
    })?;

    // Check if origin already exists
    let existing = get_cors_origins()?;
    if existing.iter().any(|o| o == origin) {
        log.error(format!("Origin already exists | origin={}", origin));
        return Err(format!("Origin '{}' already exists", origin).into());
    }

    let mut result = String::new();
    let mut in_cors_array = false;
    let mut found_cors = false;

    for line in content.lines() {
        let trimmed = line.trim();

        if trimmed.starts_with("cors_origins") && trimmed.contains('[') {
            found_cors = true;
            in_cors_array = true;

            // Handle empty array: cors_origins = []
            if trimmed.ends_with("[]") {
                result.push_str("cors_origins = [\n");
                result.push_str(&format!("    \"{}\",\n", origin));
                result.push_str("]\n");
                in_cors_array = false;
                continue;
            }
        }

        if in_cors_array && trimmed == "]" {
            // Add new origin before closing bracket
            result.push_str(&format!("    \"{}\",\n", origin));
            result.push_str(line);
            result.push('\n');
            in_cors_array = false;
            continue;
        }

        result.push_str(line);
        result.push('\n');
    }

    // If no cors_origins found, add it after [server] section
    if !found_cors {
        let mut final_result = String::new();
        let mut in_server_section = false;

        for line in result.lines() {
            final_result.push_str(line);
            final_result.push('\n');

            if line.trim() == "[server]" {
                in_server_section = true;
            }

            if in_server_section && line.trim().starts_with("bind") {
                final_result.push_str(&format!("cors_origins = [\n    \"{}\",\n]\n", origin));
                in_server_section = false;
            }
        }

        log.info(format!(
            "Writing config with new CORS origin | origin={} path={}",
            origin,
            config_path.display()
        ));
        fs::write(config_path, final_result.trim_end()).map_err(|e| {
            log.error(format!(
                "Failed to write config | path={} error={}",
                config_path.display(),
                e
            ));
            e
        })?;
    } else {
        log.info(format!(
            "Writing config with new CORS origin | origin={} path={}",
            origin,
            config_path.display()
        ));
        fs::write(config_path, result.trim_end()).map_err(|e| {
            log.error(format!(
                "Failed to write config | path={} error={}",
                config_path.display(),
                e
            ));
            e
        })?;
    }

    Ok(())
}

/// Remove a CORS origin from the config
pub fn remove_cors_origin(origin: &str) -> Result<(), Box<dyn Error>> {
    let log = ConfigLogger::new("config");
    let config_path = Path::new(CONFIG_PATH);

    log.info(format!("Reading config | path={}", config_path.display()));
    let content = fs::read_to_string(config_path).map_err(|e| {
        log.error(format!(
            "Failed to read config | path={} error={}",
            config_path.display(),
            e
        ));
        e
    })?;

    let mut result = String::new();
    let mut in_cors_array = false;
    let mut removed = false;

    for line in content.lines() {
        let trimmed = line.trim();

        if trimmed.starts_with("cors_origins") && trimmed.contains('[') {
            in_cors_array = true;
        }

        if in_cors_array {
            if trimmed == "]" {
                in_cors_array = false;
                result.push_str(line);
                result.push('\n');
                continue;
            }

            // Check if this line contains the origin to remove
            let cleaned = trimmed
                .trim_end_matches(',')
                .trim_matches('"')
                .trim_matches('\'');
            if cleaned == origin {
                removed = true;
                continue; // Skip this line
            }
        }

        result.push_str(line);
        result.push('\n');
    }

    if !removed {
        log.error(format!("CORS origin not found | origin={}", origin));
        return Err(format!("Origin '{}' not found", origin).into());
    }

    log.info(format!(
        "Writing config after removing CORS origin | origin={} path={}",
        origin,
        config_path.display()
    ));
    fs::write(config_path, result.trim_end()).map_err(|e| {
        log.error(format!(
            "Failed to write config | path={} error={}",
            config_path.display(),
            e
        ));
        e
    })?;
    Ok(())
}
