//! WIT export layer for the `logic-hooks-component` world.
//!
//! Thin adapter only: every exported call asks the host-authored
//! `crate::custom_*` override function for this pipeline point; `None`
//! maps to the SDK passthrough signal `{"passthrough": true}`,
//! `Some(json)` maps to an override. Do not edit this file to customize
//! behavior — edit the `custom_*` functions in `src/lib.rs`.
//!
//! Pattern follows `plugin/antikythera-default-hooks/src/component.rs`:
//! `wit_bindgen::generate!` against the root wit, a unit struct implementing
//! `exports::antikythera::agent_sdk::logic_hooks::Guest`, and `export!`.

// wit-bindgen emits pre-2024-edition export shims; the unsafe-op-in-
// unsafe-fn lint fires inside the generated code, not our wrapper.
#![allow(unsafe_op_in_unsafe_fn)]
// Export layer is wasm-gated; dead on native targets.
#![allow(dead_code)]

wit_bindgen::generate!({
    world: "logic-hooks-component",
    path: "../../../wit/antikythera.wit",
});

/// The SDK's passthrough signal: use default behavior at this pipeline point.
const PASSTHROUGH_JSON: &str = "{\"passthrough\": true}";

struct ExampleHooks;

impl exports::antikythera::agent_sdk::logic_hooks::Guest for ExampleHooks {
    fn prepare_turn(request_json: String, session_state_json: String) -> Result<String, String> {
        Ok(
            crate::custom_prepare_turn(&request_json, &session_state_json)
                .unwrap_or_else(|| PASSTHROUGH_JSON.to_string()),
        )
    }

    fn decide_action(
        session_state_json: String,
        llm_response_json: String,
    ) -> Result<String, String> {
        Ok(
            crate::custom_decide_action(&session_state_json, &llm_response_json)
                .unwrap_or_else(|| PASSTHROUGH_JSON.to_string()),
        )
    }

    fn handle_tool_result(
        session_state_json: String,
        tool_result_json: String,
    ) -> Result<String, String> {
        Ok(
            crate::custom_handle_tool_result(&session_state_json, &tool_result_json)
                .unwrap_or_else(|| PASSTHROUGH_JSON.to_string()),
        )
    }
}

// Wasm-only: WIT export names break rustc's ld version script on native cdylibs.
#[cfg(target_family = "wasm")]
export!(ExampleHooks);
